[".zsh/fast-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
refreshPeriod = "168h"
[".zsh/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions"
refreshPeriod = "168h"
[".zsh/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k"
refreshPeriod = "168h"
[".config/kickstart.nvim"]
type = "git-repo"
url = "https://github.com/blueputty01/kickstart.nvim"
refreshPeriod = "168h"
