[mgr]
[open]
append_rules = [
  { url = "*.pdf", use = "acrobat" },
  { url = "*/", use = [
    "edit",
    "open",
    "code",
  ] },
]
[opener]
acrobat = [
  { run = 'open -a "Adobe Acrobat.app" "$@"', desc = "Open with Acrobat", for = "macos" },
]
code = [
  { run = 'open -a "Visual Studio Code.app" "$@"', desc = "Open with Code", for = "macos" },
]
